# $OpenBSD$

COMMENT =		extensions to the Wayland protocol
DISTNAME =		wayland-protocols-1.20
CATEGORIES =		graphics
HOMEPAGE =		https://wayland.freedesktop.org/

MAINTAINER =		Vadim Zhukov <persgray@gmail.com>

# MIT, examples are GPL
PERMIT_PACKAGE =	Yes

MASTER_SITES =		https://wayland.freedesktop.org/releases/
EXTRACT_SUFX =		.tar.xz

SEPARATE_BUILD =	Yes
CONFIGURE_STYLE =	gnu

BUILD_DEPENDS =		graphics/wayland

PKG_ARCH =		*

.include <bsd.port.mk>
